<?php

/*
|--------------------------------------------------------------------------
| Tema del catálogo público
|--------------------------------------------------------------------------
|
| El catálogo es un solo diseño configurable: la tienda elige una paleta y
| tres opciones de forma. Guarda solo las claves; los valores viven acá, así
| que retocar una paleta actualiza a todas las tiendas que la usan.
|
| Los colores están copiados de prototipo-3/assets/css/paletas.css, que es la
| fuente de verdad del sistema de diseño: cada hexadecimal tiene ahí su ratio
| WCAG anotado. Si cambia una paleta, cambia primero ese archivo.
|
| 'swatches' son los cinco tonos entregados de cada paleta. No los usa el
| catálogo: son las muestras con las que el panel dibuja el selector.
|
*/

return [

    'default' => [
        'palette' => 'cafe',
        'radius' => 'square',
        'banner' => 'dark',
        'nav' => 'dark',
    ],

    /*
    | Opciones de forma. Se aplican como atributos data-* en el <html> del
    | catálogo: data-radius, data-banner y data-nav.
    */
    'options' => [

        'radius' => [
            'name' => 'Bordes',
            'values' => [
                'square' => ['name' => 'Cuadrados'],
                'round' => ['name' => 'Redondos'],
            ],
        ],

        'nav' => [
            'name' => 'Barra',
            'values' => [
                'dark' => ['name' => 'Tinta'],
                'color' => ['name' => 'De color'],
            ],
        ],

        'banner' => [
            'name' => 'Banner',
            'values' => [
                'dark' => ['name' => 'Velo oscuro'],
                'light' => ['name' => 'Velo claro'],
            ],
        ],

    ],

    'palettes' => [

        'cafe' => [
            'name' => 'Café',
            'swatches' => ['#EDE0D4', '#C9A27E', '#A47148', '#6F4E37', '#3E2C23'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#EDE0D4',
                '--color-grad-alt-2'        => '#F3EBE3',
                '--color-border'            => '#EDE0D4',
                '--color-border-strong'     => '#A47148',
                '--color-text'              => '#3E2C23',
                '--color-text-muted'        => '#6F4E37',
                '--color-text-subtle'       => '#6F4E37',
                '--color-primary'           => '#3E2C23',
                '--color-primary-hover'     => '#3E2C23',
                '--color-on-primary'        => '#EDE0D4',
                '--color-accent'            => '#6F4E37',
                '--color-accent-hover'      => '#3E2C23',
                '--color-on-accent'         => '#EDE0D4',
                '--color-accent-soft'       => '#A47148',
                '--color-accent-invert'     => '#EDE0D4',
                '--color-on-dark'           => '#EDE0D4',
                '--color-on-dark-muted'     => '#EDE0D4',
                '--color-on-dark-border'    => '#A47148',
                '--color-grad-2'            => '#6F4E37',
                '--color-nav-bg'            => '#6F4E37',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#EDE0D4',
                '--color-nav-brand'         => '#EDE0D4',
                '--color-nav-border'        => '#A47148',
                '--color-focus'             => '#6F4E37',
                '--color-focus-invert'      => '#EDE0D4',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(62, 44, 35, 0.7)',
                '--color-glass-border'      => 'rgba(237, 224, 212, 0.55)',
                '--bg-image-fallback'       => '#EDE0D4',
                '--color-banner-veil'       => 'rgba(62, 44, 35, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(237, 224, 212, 0.5)',
                '--color-on-banner-light'   => '#3E2C23',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#DE8445',
            ],
        ],

        'verano' => [
            'name' => 'Verano',
            'swatches' => ['#00C2CB', '#7FE0D4', '#FFE38A', '#FF9A76', '#FF5D8F'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#FFE38A',
                '--color-grad-alt-2'        => '#7FE0D4',
                '--color-border'            => '#FFE38A',
                '--color-border-strong'     => '#830028',
                '--color-text'              => '#830028',
                '--color-text-muted'        => '#830028',
                '--color-text-subtle'       => '#830028',
                '--color-primary'           => '#830028',
                '--color-primary-hover'     => '#67001F',
                '--color-on-primary'        => '#FFE38A',
                '--color-accent'            => '#830028',
                '--color-accent-hover'      => '#67001F',
                '--color-on-accent'         => '#FFE38A',
                '--color-accent-soft'       => '#830028',
                '--color-accent-invert'     => '#FFE38A',
                '--color-on-dark'           => '#FFE38A',
                '--color-on-dark-muted'     => '#FFE38A',
                '--color-on-dark-border'    => '#830028',
                '--color-grad-2'            => '#67001F',
                '--color-nav-bg'            => '#00C2CB',
                '--color-on-nav'            => '#830028',
                '--color-nav-active'        => '#830028',
                '--color-nav-brand'         => '#830028',
                '--color-nav-border'        => '#FFE38A',
                '--color-focus'             => '#830028',
                '--color-focus-invert'      => '#FFE38A',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(131, 0, 40, 0.7)',
                '--color-glass-border'      => 'rgba(255, 227, 138, 0.55)',
                '--bg-image-fallback'       => '#FFE38A',
                '--color-banner-veil'       => 'rgba(131, 0, 40, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(255, 227, 138, 0.5)',
                '--color-on-banner-light'   => '#830028',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#ED9BB4',
            ],
        ],

        'primavera' => [
            'name' => 'Primavera',
            'swatches' => ['#FFF3C9', '#C9E4A6', '#F7B7C4', '#A3D9C9', '#7FB4E0'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#FFF3C9',
                '--color-grad-alt-2'        => '#C9E4A6',
                '--color-border'            => '#FFF3C9',
                '--color-border-strong'     => '#184164',
                '--color-text'              => '#184164',
                '--color-text-muted'        => '#184164',
                '--color-text-subtle'       => '#184164',
                '--color-primary'           => '#184164',
                '--color-primary-hover'     => '#12314C',
                '--color-on-primary'        => '#FFF3C9',
                '--color-accent'            => '#184164',
                '--color-accent-hover'      => '#12314C',
                '--color-on-accent'         => '#FFF3C9',
                '--color-accent-soft'       => '#184164',
                '--color-accent-invert'     => '#FFF3C9',
                '--color-on-dark'           => '#FFF3C9',
                '--color-on-dark-muted'     => '#FFF3C9',
                '--color-on-dark-border'    => '#184164',
                '--color-grad-2'            => '#12314C',
                '--color-nav-bg'            => '#7FB4E0',
                '--color-on-nav'            => '#184164',
                '--color-nav-active'        => '#184164',
                '--color-nav-brand'         => '#184164',
                '--color-nav-border'        => '#FFF3C9',
                '--color-focus'             => '#184164',
                '--color-focus-invert'      => '#FFF3C9',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(24, 65, 100, 0.7)',
                '--color-glass-border'      => 'rgba(255, 243, 201, 0.55)',
                '--bg-image-fallback'       => '#FFF3C9',
                '--color-banner-veil'       => 'rgba(24, 65, 100, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(255, 243, 201, 0.5)',
                '--color-on-banner-light'   => '#184164',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#79B4E7',
            ],
        ],

        'oro' => [
            'name' => 'Oro',
            'swatches' => ['#FBF3D0', '#EBD08C', '#D4AF37', '#B8860B', '#7C5E10'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#FBF3D0',
                '--color-grad-alt-2'        => '#FCF7E0',
                '--color-border'            => '#FBF3D0',
                '--color-border-strong'     => '#B8860B',
                '--color-text'              => '#7C5E10',
                '--color-text-muted'        => '#7C5E10',
                '--color-text-subtle'       => '#7C5E10',
                '--color-primary'           => '#7C5E10',
                '--color-primary-hover'     => '#6A500E',
                '--color-on-primary'        => '#FBF3D0',
                '--color-accent'            => '#7C5E10',
                '--color-accent-hover'      => '#6A500E',
                '--color-on-accent'         => '#FBF3D0',
                '--color-accent-soft'       => '#B8860B',
                '--color-accent-invert'     => '#FBF3D0',
                '--color-on-dark'           => '#FBF3D0',
                '--color-on-dark-muted'     => '#FBF3D0',
                '--color-on-dark-border'    => '#D4AF37',
                '--color-grad-2'            => '#6A500E',
                '--color-nav-bg'            => '#7C5E10',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#FBF3D0',
                '--color-nav-brand'         => '#FBF3D0',
                '--color-nav-border'        => '#B8860B',
                '--color-focus'             => '#7C5E10',
                '--color-focus-invert'      => '#FBF3D0',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(124, 94, 16, 0.7)',
                '--color-glass-border'      => 'rgba(251, 243, 208, 0.55)',
                '--bg-image-fallback'       => '#FBF3D0',
                '--color-banner-veil'       => 'rgba(124, 94, 16, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(251, 243, 208, 0.5)',
                '--color-on-banner-light'   => '#7C5E10',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#EFE7A4',
            ],
        ],

        'arcoiris' => [
            'name' => 'Arcoíris',
            'swatches' => ['#FF5A5F', '#FFB400', '#3DDC84', '#00A6ED', '#8B5CF6'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#FFB400',
                '--color-grad-alt-2'        => '#3DDC84',
                '--color-border'            => '#FFB400',
                '--color-border-strong'     => '#FF5A5F',
                '--color-text'              => '#410ABC',
                '--color-text-muted'        => '#410ABC',
                '--color-text-subtle'       => '#410ABC',
                '--color-primary'           => '#410ABC',
                '--color-primary-hover'     => '#330892',
                '--color-on-primary'        => '#FFB400',
                '--color-accent'            => '#410ABC',
                '--color-accent-hover'      => '#330892',
                '--color-on-accent'         => '#FFB400',
                '--color-accent-soft'       => '#FF5A5F',
                '--color-accent-invert'     => '#FFB400',
                '--color-on-dark'           => '#FFB400',
                '--color-on-dark-muted'     => '#FFB400',
                '--color-on-dark-border'    => '#8B5CF6',
                '--color-grad-2'            => '#330892',
                '--color-nav-bg'            => '#3DDC84',
                '--color-on-nav'            => '#410ABC',
                '--color-nav-active'        => '#410ABC',
                '--color-nav-brand'         => '#410ABC',
                '--color-nav-border'        => '#FF5A5F',
                '--color-focus'             => '#410ABC',
                '--color-focus-invert'      => '#FFB400',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(65, 10, 188, 0.7)',
                '--color-glass-border'      => 'rgba(255, 180, 0, 0.55)',
                '--bg-image-fallback'       => '#FFB400',
                '--color-banner-veil'       => 'rgba(65, 10, 188, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(255, 180, 0, 0.5)',
                '--color-on-banner-light'   => '#410ABC',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#BBA4EF',
            ],
        ],

        'tech' => [
            'name' => 'Tech',
            'swatches' => ['#E7DFF7', '#C6B4EE', '#A48AE0', '#7B5FD1', '#4E2FB0'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#E7DFF7',
                '--color-grad-alt-2'        => '#EFEAFA',
                '--color-border'            => '#E7DFF7',
                '--color-border-strong'     => '#7B5FD1',
                '--color-text'              => '#4E2FB0',
                '--color-text-muted'        => '#4E2FB0',
                '--color-text-subtle'       => '#7B5FD1',
                '--color-primary'           => '#4E2FB0',
                '--color-primary-hover'     => '#4E2FB0',
                '--color-on-primary'        => '#E7DFF7',
                '--color-accent'            => '#7B5FD1',
                '--color-accent-hover'      => '#4E2FB0',
                '--color-on-accent'         => '#FFFFFF',
                '--color-accent-soft'       => '#7B5FD1',
                '--color-accent-invert'     => '#C6B4EE',
                '--color-on-dark'           => '#E7DFF7',
                '--color-on-dark-muted'     => '#E7DFF7',
                '--color-on-dark-border'    => '#A48AE0',
                '--color-grad-2'            => '#301D6D',
                '--color-nav-bg'            => '#7B5FD1',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#FFFFFF',
                '--color-nav-brand'         => '#E7DFF7',
                '--color-nav-border'        => '#C6B4EE',
                '--color-focus'             => '#7B5FD1',
                '--color-focus-invert'      => '#C6B4EE',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(78, 47, 176, 0.7)',
                '--color-glass-border'      => 'rgba(231, 223, 247, 0.55)',
                '--bg-image-fallback'       => '#E7DFF7',
                '--color-banner-veil'       => 'rgba(78, 47, 176, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(231, 223, 247, 0.5)',
                '--color-on-banner-light'   => '#4E2FB0',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#C4B5F2',
            ],
        ],

        'alegre' => [
            'name' => 'Alegre',
            'swatches' => ['#FF6B6B', '#FFD93D', '#6BCB77', '#4D96FF', '#FF6FB5'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#FFD93D',
                '--color-grad-alt-2'        => '#6BCB77',
                '--color-border'            => '#FFD93D',
                '--color-border-strong'     => '#003A8E',
                '--color-text'              => '#003A8E',
                '--color-text-muted'        => '#003A8E',
                '--color-text-subtle'       => '#003A8E',
                '--color-primary'           => '#003A8E',
                '--color-primary-hover'     => '#002D6D',
                '--color-on-primary'        => '#FFD93D',
                '--color-accent'            => '#003A8E',
                '--color-accent-hover'      => '#002D6D',
                '--color-on-accent'         => '#FFD93D',
                '--color-accent-soft'       => '#003A8E',
                '--color-accent-invert'     => '#FFD93D',
                '--color-on-dark'           => '#FFD93D',
                '--color-on-dark-muted'     => '#FFD93D',
                '--color-on-dark-border'    => '#003A8E',
                '--color-grad-2'            => '#002D6D',
                '--color-nav-bg'            => '#6BCB77',
                '--color-on-nav'            => '#003A8E',
                '--color-nav-active'        => '#003A8E',
                '--color-nav-brand'         => '#003A8E',
                '--color-nav-border'        => '#FF6B6B',
                '--color-focus'             => '#003A8E',
                '--color-focus-invert'      => '#FFD93D',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(0, 58, 142, 0.7)',
                '--color-glass-border'      => 'rgba(255, 217, 61, 0.55)',
                '--bg-image-fallback'       => '#FFD93D',
                '--color-banner-veil'       => 'rgba(0, 58, 142, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(255, 217, 61, 0.5)',
                '--color-on-banner-light'   => '#003A8E',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#8AB1EA',
            ],
        ],

        'invierno' => [
            'name' => 'Invierno',
            'swatches' => ['#E3F6F5', '#A7E0DB', '#5FB0C9', '#3E6D9C', '#2A2F63'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#E3F6F5',
                '--color-grad-alt-2'        => '#EDF9F8',
                '--color-border'            => '#E3F6F5',
                '--color-border-strong'     => '#3E6D9C',
                '--color-text'              => '#2A2F63',
                '--color-text-muted'        => '#3E6D9C',
                '--color-text-subtle'       => '#3E6D9C',
                '--color-primary'           => '#2A2F63',
                '--color-primary-hover'     => '#2A2F63',
                '--color-on-primary'        => '#E3F6F5',
                '--color-accent'            => '#3E6D9C',
                '--color-accent-hover'      => '#2A2F63',
                '--color-on-accent'         => '#E3F6F5',
                '--color-accent-soft'       => '#3E6D9C',
                '--color-accent-invert'     => '#E3F6F5',
                '--color-on-dark'           => '#E3F6F5',
                '--color-on-dark-muted'     => '#E3F6F5',
                '--color-on-dark-border'    => '#3E6D9C',
                '--color-grad-2'            => '#3E6D9C',
                '--color-nav-bg'            => '#3E6D9C',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#E3F6F5',
                '--color-nav-brand'         => '#E3F6F5',
                '--color-nav-border'        => '#5FB0C9',
                '--color-focus'             => '#3E6D9C',
                '--color-focus-invert'      => '#E3F6F5',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(42, 47, 99, 0.7)',
                '--color-glass-border'      => 'rgba(227, 246, 245, 0.55)',
                '--bg-image-fallback'       => '#E3F6F5',
                '--color-banner-veil'       => 'rgba(42, 47, 99, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(227, 246, 245, 0.5)',
                '--color-on-banner-light'   => '#2A2F63',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#67A6E4',
            ],
        ],

        'piel' => [
            'name' => 'Piel',
            'swatches' => ['#F8D9C0', '#E9B98F', '#D89B72', '#B87A56', '#8A5A3C'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#FAE6D5',
                '--color-grad-alt-2'        => '#FCEFE4',
                '--color-border'            => '#F8D9C0',
                '--color-border-strong'     => '#B87A56',
                '--color-text'              => '#8A5A3C',
                '--color-text-muted'        => '#8A5A3C',
                '--color-text-subtle'       => '#8A5A3C',
                '--color-primary'           => '#8A5A3C',
                '--color-primary-hover'     => '#764D33',
                '--color-on-primary'        => '#FFFFFF',
                '--color-accent'            => '#8A5A3C',
                '--color-accent-hover'      => '#764D33',
                '--color-on-accent'         => '#FFFFFF',
                '--color-accent-soft'       => '#B87A56',
                '--color-accent-invert'     => '#FBECDF',
                '--color-on-dark'           => '#FFFFFF',
                '--color-on-dark-muted'     => '#FFFFFF',
                '--color-on-dark-border'    => '#D89B72',
                '--color-grad-2'            => '#764D33',
                '--color-nav-bg'            => '#8A5A3C',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#FFFFFF',
                '--color-nav-brand'         => '#F8D9C0',
                '--color-nav-border'        => '#D89B72',
                '--color-focus'             => '#8A5A3C',
                '--color-focus-invert'      => '#FBECDF',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(138, 90, 60, 0.7)',
                '--color-glass-border'      => 'rgba(250, 230, 213, 0.55)',
                '--bg-image-fallback'       => '#FAE6D5',
                '--color-banner-veil'       => 'rgba(138, 90, 60, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(250, 230, 213, 0.5)',
                '--color-on-banner-light'   => '#8A5A3C',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#F0E9AD',
            ],
        ],

        'halloween' => [
            'name' => 'Halloween',
            'swatches' => ['#F4A100', '#E8730C', '#7A3E9D', '#3E1F47', '#1A1423'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#F4A100',
                '--color-grad-alt-2'        => '#F8C259',
                '--color-border'            => '#F4A100',
                '--color-border-strong'     => '#E8730C',
                '--color-text'              => '#1A1423',
                '--color-text-muted'        => '#3E1F47',
                '--color-text-subtle'       => '#7A3E9D',
                '--color-primary'           => '#1A1423',
                '--color-primary-hover'     => '#1A1423',
                '--color-on-primary'        => '#F4A100',
                '--color-accent'            => '#7A3E9D',
                '--color-accent-hover'      => '#1A1423',
                '--color-on-accent'         => '#FFFFFF',
                '--color-accent-soft'       => '#E8730C',
                '--color-accent-invert'     => '#F4A100',
                '--color-on-dark'           => '#F4A100',
                '--color-on-dark-muted'     => '#F4A100',
                '--color-on-dark-border'    => '#7A3E9D',
                '--color-grad-2'            => '#3E1F47',
                '--color-nav-bg'            => '#7A3E9D',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#FFFFFF',
                '--color-nav-brand'         => '#F4A100',
                '--color-nav-border'        => '#E8730C',
                '--color-focus'             => '#7A3E9D',
                '--color-focus-invert'      => '#F4A100',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(26, 20, 35, 0.7)',
                '--color-glass-border'      => 'rgba(244, 161, 0, 0.55)',
                '--bg-image-fallback'       => '#F4A100',
                '--color-banner-veil'       => 'rgba(26, 20, 35, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(244, 161, 0, 0.5)',
                '--color-on-banner-light'   => '#1A1423',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#B25FE3',
            ],
        ],

        'frio' => [
            'name' => 'Frío',
            'swatches' => ['#C1D993', '#A7D078', '#B560E1', '#7C63BB', '#6941B0'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#C1D993',
                '--color-grad-alt-2'        => '#D7E6B9',
                '--color-border'            => '#C1D993',
                '--color-border-strong'     => '#B560E1',
                '--color-text'              => '#6941B0',
                '--color-text-muted'        => '#6941B0',
                '--color-text-subtle'       => '#7C63BB',
                '--color-primary'           => '#6941B0',
                '--color-primary-hover'     => '#6941B0',
                '--color-on-primary'        => '#C1D993',
                '--color-accent'            => '#7C63BB',
                '--color-accent-hover'      => '#6941B0',
                '--color-on-accent'         => '#FFFFFF',
                '--color-accent-soft'       => '#B560E1',
                '--color-accent-invert'     => '#C1D993',
                '--color-on-dark'           => '#C1D993',
                '--color-on-dark-muted'     => '#C1D993',
                '--color-on-dark-border'    => '#B560E1',
                '--color-grad-2'            => '#41286D',
                '--color-nav-bg'            => '#6941B0',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#C1D993',
                '--color-nav-brand'         => '#A7D078',
                '--color-nav-border'        => '#B560E1',
                '--color-focus'             => '#7C63BB',
                '--color-focus-invert'      => '#C1D993',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(105, 65, 176, 0.7)',
                '--color-glass-border'      => 'rgba(193, 217, 147, 0.55)',
                '--bg-image-fallback'       => '#C1D993',
                '--color-banner-veil'       => 'rgba(105, 65, 176, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(193, 217, 147, 0.5)',
                '--color-on-banner-light'   => '#6941B0',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#D1D2EB',
            ],
        ],

        'noche' => [
            'name' => 'Noche',
            'swatches' => ['#1F4973', '#3124A5', '#392184', '#17224D', '#271538'],
            'colors' => [
                '--color-bg'                => '#FFFFFF',
                '--color-surface'           => '#FFFFFF',
                '--color-surface-alt'       => '#4B8DCF',
                '--color-grad-alt-2'        => '#8AB5E0',
                '--color-border'            => '#1F4973',
                '--color-border-strong'     => '#3124A5',
                '--color-text'              => '#271538',
                '--color-text-muted'        => '#271538',
                '--color-text-subtle'       => '#392184',
                '--color-primary'           => '#271538',
                '--color-primary-hover'     => '#271538',
                '--color-on-primary'        => '#FFFFFF',
                '--color-accent'            => '#3124A5',
                '--color-accent-hover'      => '#271538',
                '--color-on-accent'         => '#FFFFFF',
                '--color-accent-soft'       => '#3124A5',
                '--color-accent-invert'     => '#8A80E3',
                '--color-on-dark'           => '#FFFFFF',
                '--color-on-dark-muted'     => '#FFFFFF',
                '--color-on-dark-border'    => '#1F4973',
                '--color-grad-2'            => '#17224D',
                '--color-nav-bg'            => '#1F4973',
                '--color-on-nav'            => '#FFFFFF',
                '--color-nav-active'        => '#FFFFFF',
                '--color-nav-brand'         => '#FFFFFF',
                '--color-nav-border'        => '#3124A5',
                '--color-focus'             => '#3124A5',
                '--color-focus-invert'      => '#8A80E3',
                '--color-glass'             => 'rgba(255, 255, 255, 0.7)',
                '--color-glass-dark'        => 'rgba(39, 21, 56, 0.7)',
                '--color-glass-border'      => 'rgba(75, 141, 207, 0.55)',
                '--bg-image-fallback'       => '#4B8DCF',
                '--color-banner-veil'       => 'rgba(39, 21, 56, 0.5)',
                '--color-on-banner'         => '#FFFFFF',
                '--color-banner-veil-light' => 'rgba(75, 141, 207, 0.5)',
                '--color-on-banner-light'   => '#271538',
                '--color-footer-text'       => '#FFFFFF',
                '--color-brand-1'           => '#FFFFFF',
                '--color-brand-2'           => '#8C81E9',
            ],
        ],

    ],

];
